version: '2'

services:
  webserver:
    build: ./docker/webserver
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    image: runwaytest_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/c_ouhajjou/Repos/xdebug-docker/www:/var/www/html
